# A unique project reference for your Supabase project
project_id = "localguru"

[api]
# Port to use for the API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]

[db]
# Port to use for the local database URL
port = 54322
# Database major version to use
major_version = 15

[studio]
# Port to use for Supabase Studio
port = 54323

[inbucket]
# Port to use for the email testing server web interface
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in emails.
site_url = "http://localhost:3000"
# A list of URLs that auth redirects to by default when no redirect_to is specified.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Default: 3600 (1 hour)
jwt_expiry = 3600
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old and new email addresses.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false 