name: Daily Reddit Data Update

on:
  schedule:
    # Run at 4:30 AM UTC (adjust as needed for your timezone)
    - cron: '30 4 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update-reddit-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Verify file structure
        run: |
          echo "=== Repository structure ==="
          find localguru-ingestion -type f -name "*.ts" | grep -v "node_modules" | sort
          echo "=== Checking for daily script ==="
          ls -la localguru-ingestion/src/scripts/daily-reddit-update.ts || echo "File not found"
      
      - name: Install dependencies
        run: |
          cd localguru-ingestion
          npm ci
          
          # List installed packages for debugging
          echo "=== Installed packages ==="
          npm list --depth=0
      
      - name: Create logs directory
        run: |
          cd localguru-ingestion
          mkdir -p logs
      
      - name: Run Reddit update script with verbose logging
        env:
          # Supabase credentials
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          
          # Reddit API credentials
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: "LocalGuru/1.0 (by /u/${{ secrets.REDDIT_USERNAME }})"
          
          # Development mode for verbose logging
          NODE_ENV: "development"
        run: |
          cd localguru-ingestion
          DATE=$(date +%Y-%m-%d)
          LOG_FILE="logs/reddit-$DATE.log"
          
          echo "========== Starting Reddit update at $(date) ==========" > $LOG_FILE
          echo "=== Environment ===" >> $LOG_FILE
          echo "Node version: $(node -v)" >> $LOG_FILE
          echo "NPM version: $(npm -v)" >> $LOG_FILE
          echo "Working directory: $(pwd)" >> $LOG_FILE
          echo "Script path exists: $(test -f src/scripts/daily-reddit-update.ts && echo 'Yes' || echo 'No')" >> $LOG_FILE
          echo "Reddit credentials set: $(test -n "$REDDIT_CLIENT_ID" && echo 'Yes' || echo 'No')" >> $LOG_FILE
          echo "=== Starting script execution ===" >> $LOG_FILE
          
          # Run with more verbose output
          npx ts-node --transpile-only src/scripts/daily-reddit-update.ts >> $LOG_FILE 2>&1
          EXIT_CODE=$?
          
          echo "========== Finished at $(date) with exit code $EXIT_CODE ==========" >> $LOG_FILE
          
          # Output last 50 lines of log for immediate visibility in GitHub Actions
          echo "=== Last 50 lines of log ==="
          tail -n 50 $LOG_FILE
          
          # Set output for log filename
          echo "log_filename=reddit-$DATE.log" >> $GITHUB_OUTPUT
          
          # Exit with the same code as the script
          exit $EXIT_CODE
        id: run_script
      
      - name: Upload log as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reddit-update-logs
          path: localguru-ingestion/logs/${{ steps.run_script.outputs.log_filename }}
          retention-days: 7
      
      # Optional email notification - manually added when needed
      # Uncomment and configure this section after setting up email secrets
      # 
      # - name: Send failure notification
      #   if: failure()
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: ${{ secrets.MAIL_SERVER }}
      #     server_port: ${{ secrets.MAIL_PORT }}
      #     username: ${{ secrets.MAIL_USERNAME }}
      #     password: ${{ secrets.MAIL_PASSWORD }}
      #     subject: "❌ Reddit Data Update Failed"
      #     body: |
      #       The daily Reddit data update job failed.
      #       
      #       Repository: ${{ github.repository }}
      #       Workflow: ${{ github.workflow }}
      #       Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #       
      #       Please check the logs for more details.
      #     to: ${{ secrets.MAIL_RECIPIENT }}
      #     from: GitHub Actions 